name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest

      - name: Build APK
        env:
          ANDROIDSDK: ${{ github.workspace }}/../android-sdk
          ANDROIDNDK: ${{ github.workspace }}/../android-sdk/ndk/25.2.9519653
          PATH: ${{ github.workspace }}/../android-sdk/platform-tools:${{ github.workspace }}/../android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/../android-sdk/build-tools/33.0.2:$PATH
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: habit-tracker-apk
          path: bin/*.apk
